const Trucks = [
  {
    id: 1,
    name: "Mahindra Bolero Maxitruck Plus",
    company: "Mahindra",
    price: "7.15 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Ashok Leyland Dost+",
    company: "Ashok Leyland",
    price: "8.20 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Ashok Leyland BADA DOST",
    company: "Ashok Leyland",
    price: "8 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Mahindra Bolero Camper",
    company: "Mahindra",
    price: "9.5 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Mahindra Bolero Pikup 4X4",
    company: "Mahindra",
    price: "9.2 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Mahindra Supro Minitruck",
    company: "Mahindra",
    price: "7.22 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Maruti Suzuki Eeco Cargo",
    company: "Maruti Suzuki",
    price: "4.55 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: " Tata Yodha Pickup",
    company: "Tata",
    price: "9.23 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Isuzu S-CAB",
    company: "Isuzu",
    price: "10.05 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
  {
    id: 1,
    name: "Mahindra Imperio",
    company: "Mahindra",
    price: "8.24 Lakh",
    year: "2011",
    image: "https://www.cars24.com/blog/wp-content/uploads/2021/04/dost.jpg",
  },
];

module.exports ={ Trucks};